### ISSUE TITLE
Static Class Diagram

### ISSUE THREAD

**Issue by ATrulyRandomGuy** [CTOverton/CMPSC_488#13]
Create static class diagrams [located here](https://drive.google.com/drive/u/0/folders/1AUG1pEwKvPmZzLkqby6YOJQe5XffVNbw) using draw.io. Reference sequence diagrams [created here](https://drive.google.com/open?id=1OtjXinGJYOhLFOCn2B6czq8gaTvOdgfe). Guidelines can be [found here](https://turing.cs.hbg.psu.edu/cmpsc488/Phase2-guidance.pdf).

- [x] User - Signup
- [x] User - Edit Details
- [x] User - Create an event
- [x] Trip Coordinator - Edit Trip Details
- [x] Trip Coordinator - Add Invite Attendees
- [x] Trip Coordinator - Send Invite Email
- [x] Trip Coordinator - Mark Attendance - QR code
- [x] Attendees - Mark Attendance - Instant Link

**Comment by CTOverton** [comment]
Completed
