### ISSUE TITLE
High-level Requirements (≥10)

### ISSUE THREAD

**Issue by CTOverton** [CTOverton/CMPSC_488#5]
Create High Level Requirements for Application

### [Edit document here](https://drive.google.com/open?id=1FteQskru5OLbFIQqIJjs4cIolZ93uYhOhmeM5FKIPC8)

**Comment by ATrulyRandomGuy** [comment]
https://link.springer.com/content/pdf/10.1007%2F978-1-4302-0369-8.pdf
pg 30 details the High-Level Requirements. Started on this, but we should back up and discuss what we are making in fullness.

![image](https://user-images.githubusercontent.com/54868718/72917552-0de46900-3d12-11ea-9fde-280b235b72aa.png)

**Comment by CTOverton** [comment]
Completed!
